version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ".env"
    volumes:
      - "./files:/usr/src/app/files"
      - "./keys:/usr/src/app/keys"
    command: >
      sh -c "rm -rf /usr/src/app/tmp/*
      && node index.js"